python3 ../train_model.py \
    --activation-dropout 0.0 \
    --dropout 0.0 \
    --checkpoints \
    --embed-dim 32 \
    --ffn-dim 64 \
    --fsdp \
    --layers 1 \
    --lr 0.001 \
    --model retnet \
    --heads 8 \
    --seq-len 128 \
    --value-embed-dim 32 \
    --vocab-size 28783 \
    --device cpu \
    --epochs 10 \
    --batch-size 128 \
    --rand-seed 42 \
